// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnhouozkdfxphudrjbvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBuaG91b3prZGZ4cGh1ZHJqYnZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkyMTA1NjMsImV4cCI6MjA5NDc4NjU2M30.XsHyBBlfCBWAiXdeU5P4oLAYRn80udOlzBd7o9nmcW4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});